// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trabalho;

#nullable disable

namespace ChatEscola.Migrations
{
    [DbContext(typeof(ChatEscolaDB))]
    partial class ChatEscolaDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Trabalho.Aluno", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Turmaid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("Turmaid");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Trabalho.Disciplina", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("diaSemana")
                        .HasColumnType("TEXT");

                    b.Property<string>("horario")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("Trabalho.Ensalamento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("idProfessor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idSala")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idTurma")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Ensalamentos");
                });

            modelBuilder.Entity("Trabalho.Professor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("diaDisponivel")
                        .HasColumnType("TEXT");

                    b.Property<string>("horarioDisponivel")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("nomeDisciplina")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("Trabalho.Sala", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("capacidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("Trabalho.Turma", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("idDisciplina")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nomeDisciplina")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("Trabalho.Aluno", b =>
                {
                    b.HasOne("Trabalho.Turma", null)
                        .WithMany("alunos")
                        .HasForeignKey("Turmaid");
                });

            modelBuilder.Entity("Trabalho.Turma", b =>
                {
                    b.Navigation("alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
